{
  "keyLength": 2048,
  "io": false,
  "webUrl": "https://update-0001.jindianle.com/hot_code_com.github.emudvv.smdt_dist/koudai/",
  "thirdPartUrlPrefix": [
    "https://cash.yeepay.com",
    "https://m.51yueqian.com",
    "https://wap.beeplaying.com",
    "http://cash.yeepay.com",
    "http://m.51yueqian.com",
    "http://wap.beeplaying.com",
    "https://itou.caihongduoduo.com",
    "http://itou.caihongduoduo.com",
    "http://koudai.jindianle.com/others/scheme/index.html",
    "https://koudai.jindianle.com/others/scheme/index.html",
    "https://youdian.jindianle.com/others/scheme/index.html",
    "http://youdian.jindianle.com/others/scheme/index.html",
    "https://h5.sim.51yueqian.net",
    "http://h5.sim.51yueqian.net",
    "https://engine.qazxsdc.com/index/activity",
    "http://engine.qazxsdc.com/index/activity",
    "https://activity4.xinxuezl.com/activity",
    "http://activity4.xinxuezl.com/activity",
    "https://youliao.honghuoshop.com/",
    "http://youliao.honghuoshop.com/",
    "https://jingfen.jd.com"
  ],
  "androidThirdPartUrlPrefix": [
    "https://cash.yeepay.com",
    "https://m.51yueqian.com",
    "https://wap.beeplaying.com",
    "https://h5.jdddata.com/communal/cartoonKou/fulllive",
    "http://cash.yeepay.com",
    "http://m.51yueqian.com",
    "http://wap.beeplaying.com",
    "http://h5.jdddata.com/communal/cartoonKou/fulllive",
    "https://itou.caihongduoduo.com",
    "http://itou.caihongduoduo.com",
    "http://koudai.jindianle.com/others/scheme/index.html",
    "https://koudai.jindianle.com/others/scheme/index.html",
    "https://youdian.jindianle.com/others/scheme/index.html",
    "http://youdian.jindianle.com/others/scheme/index.html",
    "https://h5.sim.51yueqian.net",
    "http://h5.sim.51yueqian.net",
    "https://youliao.honghuoshop.com/",
    "http://youliao.honghuoshop.com/",
    "https://jingfen.jd.com"
  ],
  "schemeLaunchUrl": [
    "weixin://",
    "sms://",
    "tel://",
    "alipays://",
    "mailto:",
    "chsp://",
    "simclient://"
  ],
  "syncCookiesUrl": "https://www.jindianle.com",
  "hotCodeUrl": "https://update-0001.jindianle.com/hot_code_com.github.emudvv.smdt_dist/koudai/",
  "hotCodeZipUrl": "https://update-0001.jindianle.com/hot_code_com.github.emudvv.smdt_dist/koudai_zip/",
  "enableHotCode": true,
  "enableHotCodeZip": true,
  "enableBlue": false,
  "dsn": "https://bb07f385190d468ab0a268d58d4073fb@o423880.ingest.sentry.io/5354926",
  "reloadDelay": 250
}
